{
 "title": "🌤️ Weather Live Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "New York Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT city, temperature_c as Temperature, wind_speed_ms as  WindSpeed, timestamp\nFROM weather.readings\nwhere city='New York'\nOrder by timestamp desc\nlimit 1\nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Tokyo Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT city, temperature_c as Temperature, wind_speed_ms as  WindSpeed, timestamp\nFROM weather.readings\nwhere city='Tokyo'\nOrder by timestamp desc\nlimit 1\nALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "London Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT city, temperature_c as Temperature, wind_speed_ms as  WindSpeed, timestamp\nFROM weather.readings\nwhere city='London'\nOrder by timestamp desc\nlimit 1\nALLOW FILTERING;"
    }
   ]
  }
 ]
}